import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../data/repositories/playlist_repository.dart';
import '../application/playlist_controller.dart';

/// Lets the user add a single song to an existing or new playlist, e.g. from
/// Song Discovery's or Now Playing's "add to playlist" action (Screens.md
/// #8). The inverse of [AddSongsSheet], which adds many songs to one
/// playlist.
class AddToPlaylistSheet extends ConsumerWidget {
  const AddToPlaylistSheet({super.key, required this.songId});

  final String songId;

  static Future<void> show(BuildContext context, String songId) {
    return showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      builder: (_) => AddToPlaylistSheet(songId: songId),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final playlists = ref.watch(playlistsStreamProvider);

    return DraggableScrollableSheet(
      expand: false,
      builder: (context, scrollController) => playlists.when(
        data: (items) => ListView(
          controller: scrollController,
          children: [
            ListTile(
              leading: const Icon(Icons.add),
              title: const Text('New playlist'),
              onTap: () => _createAndAdd(context, ref),
            ),
            if (items.isEmpty)
              const Padding(
                padding: EdgeInsets.all(32),
                child: Center(child: Text('No playlists yet.')),
              ),
            for (final playlist in items)
              ListTile(
                leading: Icon(
                  playlist.isAutoGenerated
                      ? Icons.auto_awesome
                      : Icons.queue_music,
                ),
                title: Text(playlist.name),
                onTap: () async {
                  await ref
                      .read(playlistRepositoryProvider)
                      .addSong(playlist.id, songId);
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('Added to ${playlist.name}.')),
                    );
                    Navigator.of(context).pop();
                  }
                },
              ),
          ],
        ),
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error, _) =>
            Center(child: Text('Failed to load playlists: $error')),
      ),
    );
  }

  Future<void> _createAndAdd(BuildContext context, WidgetRef ref) async {
    final controller = TextEditingController();
    final name = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('New playlist'),
        content: TextField(
          controller: controller,
          autofocus: true,
          decoration: const InputDecoration(hintText: 'Playlist name'),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(controller.text.trim()),
            child: const Text('Create'),
          ),
        ],
      ),
    );
    if (name == null || name.isEmpty) return;

    final playlist = await ref
        .read(playlistRepositoryProvider)
        .createPlaylist(name);
    await ref.read(playlistRepositoryProvider).addSong(playlist.id, songId);
    if (context.mounted) Navigator.of(context).pop();
  }
}
