import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';

import '../../../core/utils/song_search.dart';
import '../../../data/models/playlist.dart';
import '../../../data/models/song.dart';
import '../../../data/repositories/playlist_repository.dart';
import '../../../shared/widgets/app_bar_icon_action.dart';
import '../../../shared/widgets/app_search_field.dart';
import '../../../shared/widgets/gradient_app_bar.dart';
import '../../../shared/widgets/mini_player.dart';
import '../../../shared/widgets/play_shuffle_header.dart';
import '../../../shared/widgets/song_list_tile.dart';
import '../../playback/application/playback_controller.dart';
import '../application/playlist_controller.dart';
import 'add_songs_sheet.dart';
import 'playlist_edit_dialog.dart';

enum _PlaylistSort { playlistOrder, title, artist, duration }

/// View and manage the songs within a specific playlist (Screens.md #5),
/// with play/shuffle header actions, search, and view sorting. Drag
/// reordering (which edits the stored order) is only available in the
/// default playlist-order view with no search active.
class PlaylistDetailScreen extends ConsumerStatefulWidget {
  const PlaylistDetailScreen({super.key, required this.playlistId});

  final String playlistId;

  @override
  ConsumerState<PlaylistDetailScreen> createState() =>
      _PlaylistDetailScreenState();
}

class _PlaylistDetailScreenState extends ConsumerState<PlaylistDetailScreen> {
  String _query = '';
  _PlaylistSort _sort = _PlaylistSort.playlistOrder;

  bool get _isCustomView =>
      _query.trim().isNotEmpty || _sort != _PlaylistSort.playlistOrder;

  List<Song> _visibleSongs(List<Song> songs) {
    final visible = songs
        .where((song) => songMatchesQuery(song, _query))
        .toList();
    switch (_sort) {
      case _PlaylistSort.playlistOrder:
        break;
      case _PlaylistSort.title:
        visible.sort(
          (a, b) => a.title.toLowerCase().compareTo(b.title.toLowerCase()),
        );
      case _PlaylistSort.artist:
        visible.sort(
          (a, b) => a.artist.toLowerCase().compareTo(b.artist.toLowerCase()),
        );
      case _PlaylistSort.duration:
        visible.sort((a, b) => a.duration.compareTo(b.duration));
    }
    return visible;
  }

  @override
  Widget build(BuildContext context) {
    final detail = ref.watch(playlistDetailProvider(widget.playlistId));
    final playlist = detail.value?.playlist;
    final songs = detail.value?.songs ?? const <Song>[];
    final scheme = Theme.of(context).colorScheme;

    return Scaffold(
      bottomNavigationBar: const MiniPlayer(),
      appBar: GradientAppBar(
        title: Text(playlist?.name ?? 'Playlist'),
        actions: [
          AppBarIconAction(
            icon: const Icon(Icons.playlist_add),
            tooltip: 'Add songs',
            onPressed: () => AddSongsSheet.show(context, widget.playlistId),
          ),
          if (playlist != null) ...[
            AppBarIconAction(
              icon: const Icon(Icons.share_outlined),
              tooltip: 'Share',
              onPressed: () => _share(playlist, songs),
            ),
            if (!playlist.isAutoGenerated) ...[
              AppBarIconAction(
                icon: const Icon(Icons.edit_outlined),
                tooltip: 'Edit',
                onPressed: () => _editPlaylist(context, playlist),
              ),
              AppBarIconAction(
                icon: const Icon(Icons.delete_outline),
                tooltip: 'Delete',
                onPressed: () => _confirmDelete(context, playlist),
              ),
            ],
          ],
          const SizedBox(width: 4),
        ],
      ),
      body: detail.when(
        data: (value) {
          if (value == null) {
            return const Center(child: Text('Playlist not found.'));
          }
          final visible = _visibleSongs(value.songs);
          return CustomScrollView(
            slivers: [
              SliverToBoxAdapter(
                child: _PlaylistHeader(playlist: value.playlist),
              ),
              SliverToBoxAdapter(
                child: PlayShuffleHeader(
                  songs: value.songs,
                  sourcePlaylistId: widget.playlistId,
                ),
              ),
              SliverToBoxAdapter(
                child: Padding(
                  padding: const EdgeInsets.fromLTRB(16, 8, 16, 8),
                  child: Row(
                    children: [
                      Expanded(
                        child: AppSearchField(
                          hint: 'Search in playlist',
                          onChanged: (query) => setState(() => _query = query),
                        ),
                      ),
                      const SizedBox(width: 8),
                      DecoratedBox(
                        decoration: BoxDecoration(
                          color: scheme.surfaceContainerHighest.withValues(
                            alpha: 0.6,
                          ),
                          shape: BoxShape.circle,
                        ),
                        child: PopupMenuButton<_PlaylistSort>(
                          icon: Icon(Icons.sort, color: scheme.primary),
                          tooltip: 'Sort',
                          initialValue: _sort,
                          onSelected: (value) => setState(() => _sort = value),
                          itemBuilder: (_) => const [
                            PopupMenuItem(
                              value: _PlaylistSort.playlistOrder,
                              child: Text('Playlist order'),
                            ),
                            PopupMenuItem(
                              value: _PlaylistSort.title,
                              child: Text('Title'),
                            ),
                            PopupMenuItem(
                              value: _PlaylistSort.artist,
                              child: Text('Artist'),
                            ),
                            PopupMenuItem(
                              value: _PlaylistSort.duration,
                              child: Text('Length'),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              if (value.songs.isEmpty)
                const SliverToBoxAdapter(
                  child: Padding(
                    padding: EdgeInsets.all(32),
                    child: Center(
                      child: Text('No songs in this playlist yet.'),
                    ),
                  ),
                )
              else if (visible.isEmpty)
                const SliverToBoxAdapter(
                  child: Padding(
                    padding: EdgeInsets.all(32),
                    child: Center(child: Text('No songs match.')),
                  ),
                )
              else if (_isCustomView)
                SliverList.builder(
                  itemCount: visible.length,
                  itemBuilder: (context, index) => _songTile(visible, index),
                )
              else
                SliverReorderableList(
                  itemCount: visible.length,
                  onReorderItem: (oldIndex, newIndex) {
                    final reordered = [...value.songs];
                    final moved = reordered.removeAt(oldIndex);
                    reordered.insert(newIndex, moved);
                    ref
                        .read(playlistRepositoryProvider)
                        .reorderSongs(
                          widget.playlistId,
                          reordered.map((s) => s.id).toList(),
                        );
                  },
                  itemBuilder: (context, index) =>
                      ReorderableDelayedDragStartListener(
                        key: ValueKey(visible[index].id),
                        index: index,
                        child: _songTile(visible, index),
                      ),
                ),
            ],
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error, _) =>
            Center(child: Text('Failed to load playlist: $error')),
      ),
    );
  }

  Widget _songTile(List<Song> queue, int index) {
    final song = queue[index];
    return SongListTile(
      key: _isCustomView ? ValueKey(song.id) : null,
      song: song,
      onTap: () => ref
          .read(playbackControllerProvider.notifier)
          .playQueue(
            queue,
            startIndex: index,
            sourcePlaylistId: widget.playlistId,
          ),
      trailing: IconButton(
        icon: const Icon(Icons.remove_circle_outline),
        tooltip: 'Remove from playlist',
        onPressed: () => ref
            .read(playlistRepositoryProvider)
            .removeSong(widget.playlistId, song.id),
      ),
    );
  }

  Future<void> _share(Playlist playlist, List<Song> songs) async {
    final trackList = [
      for (final song in songs) '${song.title} — ${song.artist}',
    ].join('\n');
    await SharePlus.instance.share(
      ShareParams(
        text: songs.isEmpty ? playlist.name : '${playlist.name}\n\n$trackList',
      ),
    );
  }

  Future<void> _editPlaylist(BuildContext context, Playlist playlist) async {
    final result = await showPlaylistEditDialog(
      context,
      title: 'Edit playlist',
      initialValue: playlist.name,
      showCoverPicker: true,
      currentCoverPath: playlist.coverImagePath,
    );
    if (result == null) return;

    final repository = ref.read(playlistRepositoryProvider);
    if (result.name.isNotEmpty && result.name != playlist.name) {
      await repository.renamePlaylist(playlist.id, result.name);
    }
    if (result.coverImagePath != null) {
      await repository.setCoverImage(playlist.id, result.coverImagePath!);
    }
  }

  Future<void> _confirmDelete(BuildContext context, Playlist playlist) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Delete "${playlist.name}"?'),
        content: const Text(
          'This removes the playlist. Your songs stay in your library.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(true),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
    if (confirmed == true) {
      await ref.read(playlistRepositoryProvider).deletePlaylist(playlist.id);
      if (context.mounted) Navigator.of(context).pop();
    }
  }
}

class _PlaylistHeader extends StatelessWidget {
  const _PlaylistHeader({required this.playlist});

  final Playlist playlist;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final coverPath = playlist.coverImagePath;

    return Padding(
      padding: const EdgeInsets.all(24),
      child: Column(
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(20),
            child: coverPath != null
                ? Image.file(
                    File(coverPath),
                    width: 160,
                    height: 160,
                    fit: BoxFit.cover,
                  )
                : Container(
                    width: 160,
                    height: 160,
                    color: scheme.surfaceContainerHighest,
                    child: Icon(
                      playlist.isAutoGenerated
                          ? Icons.auto_awesome
                          : Icons.queue_music,
                      size: 56,
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
          ),
          const SizedBox(height: 16),
          Text(
            playlist.name,
            textAlign: TextAlign.center,
            style: Theme.of(context).textTheme.headlineSmall,
          ),
        ],
      ),
    );
  }
}
