import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';

import '../../../data/models/playlist.dart';
import '../../../data/models/song.dart';
import '../../../data/repositories/playlist_repository.dart';
import '../../../shared/widgets/app_bar_icon_action.dart';
import '../../../shared/widgets/gradient_app_bar.dart';
import '../../../shared/widgets/gradient_button.dart';
import '../../../shared/widgets/song_list_tile.dart';
import '../../playback/application/playback_controller.dart';
import '../application/playlist_controller.dart';
import 'add_songs_sheet.dart';
import 'playlist_edit_dialog.dart';

/// View and manage the songs within a specific playlist (Screens.md #5).
class PlaylistDetailScreen extends ConsumerWidget {
  const PlaylistDetailScreen({super.key, required this.playlistId});

  final String playlistId;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final detail = ref.watch(playlistDetailProvider(playlistId));
    final playlist = detail.value?.playlist;
    final songs = detail.value?.songs ?? const [];

    return Scaffold(
      appBar: GradientAppBar(
        title: Text(playlist?.name ?? 'Playlist'),
        actions: [
          AppBarIconAction(
            icon: const Icon(Icons.playlist_add),
            tooltip: 'Add songs',
            onPressed: () => AddSongsSheet.show(
              context,
              playlistId,
              songs.map((song) => song.id).toSet(),
            ),
          ),
          if (playlist != null) ...[
            AppBarIconAction(
              icon: const Icon(Icons.share_outlined),
              tooltip: 'Share',
              onPressed: () => _share(playlist, songs),
            ),
            if (!playlist.isAutoGenerated) ...[
              AppBarIconAction(
                icon: const Icon(Icons.edit_outlined),
                tooltip: 'Edit',
                onPressed: () => _editPlaylist(context, ref, playlist),
              ),
              AppBarIconAction(
                icon: const Icon(Icons.delete_outline),
                tooltip: 'Delete',
                onPressed: () => _confirmDelete(context, ref, playlist),
              ),
            ],
          ],
          const SizedBox(width: 4),
        ],
      ),
      body: detail.when(
        data: (value) {
          if (value == null) {
            return const Center(child: Text('Playlist not found.'));
          }
          return CustomScrollView(
            slivers: [
              SliverToBoxAdapter(
                child: _PlaylistHeader(playlist: value.playlist),
              ),
              if (value.songs.isEmpty)
                const SliverToBoxAdapter(
                  child: Padding(
                    padding: EdgeInsets.all(32),
                    child: Center(
                      child: Text('No songs in this playlist yet.'),
                    ),
                  ),
                )
              else
                SliverReorderableList(
                  itemCount: value.songs.length,
                  onReorderItem: (oldIndex, newIndex) {
                    final reordered = [...value.songs];
                    final moved = reordered.removeAt(oldIndex);
                    reordered.insert(newIndex, moved);
                    ref
                        .read(playlistRepositoryProvider)
                        .reorderSongs(
                          playlistId,
                          reordered.map((s) => s.id).toList(),
                        );
                  },
                  itemBuilder: (context, index) {
                    final song = value.songs[index];
                    return ReorderableDelayedDragStartListener(
                      key: ValueKey(song.id),
                      index: index,
                      child: SongListTile(
                        song: song,
                        onTap: () => ref
                            .read(playbackControllerProvider.notifier)
                            .playQueue(
                              value.songs,
                              startIndex: index,
                              sourcePlaylistId: playlistId,
                            ),
                        trailing: IconButton(
                          icon: const Icon(Icons.remove_circle_outline),
                          tooltip: 'Remove from playlist',
                          onPressed: () => ref
                              .read(playlistRepositoryProvider)
                              .removeSong(playlistId, song.id),
                        ),
                      ),
                    );
                  },
                ),
            ],
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error, _) =>
            Center(child: Text('Failed to load playlist: $error')),
      ),
      floatingActionButton: songs.isEmpty
          ? null
          : GradientFab(
              icon: Icons.play_arrow,
              tooltip: 'Play all',
              onPressed: () => ref
                  .read(playbackControllerProvider.notifier)
                  .playQueue(
                    songs,
                    startIndex: 0,
                    sourcePlaylistId: playlistId,
                  ),
            ),
    );
  }

  Future<void> _share(Playlist playlist, List<Song> songs) async {
    final trackList = [
      for (final song in songs) '${song.title} — ${song.artist}',
    ].join('\n');
    await SharePlus.instance.share(
      ShareParams(
        text: songs.isEmpty ? playlist.name : '${playlist.name}\n\n$trackList',
      ),
    );
  }

  Future<void> _editPlaylist(
    BuildContext context,
    WidgetRef ref,
    Playlist playlist,
  ) async {
    final result = await showPlaylistEditDialog(
      context,
      title: 'Edit playlist',
      initialValue: playlist.name,
      showCoverPicker: true,
      currentCoverPath: playlist.coverImagePath,
    );
    if (result == null) return;

    final repository = ref.read(playlistRepositoryProvider);
    if (result.name.isNotEmpty && result.name != playlist.name) {
      await repository.renamePlaylist(playlist.id, result.name);
    }
    if (result.coverImagePath != null) {
      await repository.setCoverImage(playlist.id, result.coverImagePath!);
    }
  }

  Future<void> _confirmDelete(
    BuildContext context,
    WidgetRef ref,
    Playlist playlist,
  ) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Delete "${playlist.name}"?'),
        content: const Text(
          'This removes the playlist. Your songs stay in your library.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(true),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
    if (confirmed == true) {
      await ref.read(playlistRepositoryProvider).deletePlaylist(playlist.id);
      if (context.mounted) Navigator.of(context).pop();
    }
  }
}

class _PlaylistHeader extends StatelessWidget {
  const _PlaylistHeader({required this.playlist});

  final Playlist playlist;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final coverPath = playlist.coverImagePath;

    return Padding(
      padding: const EdgeInsets.all(24),
      child: Column(
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(20),
            child: coverPath != null
                ? Image.file(
                    File(coverPath),
                    width: 160,
                    height: 160,
                    fit: BoxFit.cover,
                  )
                : Container(
                    width: 160,
                    height: 160,
                    color: scheme.surfaceContainerHighest,
                    child: Icon(
                      playlist.isAutoGenerated
                          ? Icons.auto_awesome
                          : Icons.queue_music,
                      size: 56,
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
          ),
          const SizedBox(height: 16),
          Text(
            playlist.name,
            textAlign: TextAlign.center,
            style: Theme.of(context).textTheme.headlineSmall,
          ),
        ],
      ),
    );
  }
}
