import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../data/models/playlist.dart';
import '../../../data/repositories/playlist_repository.dart';
import '../application/playlist_controller.dart';
import 'playlist_detail_screen.dart';

/// Shows all user-created playlists plus auto-generated mood/energy
/// playlists (Screens.md #4). Embedded as a tab within the Library shell.
class PlaylistListScreen extends ConsumerWidget {
  const PlaylistListScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final playlists = ref.watch(playlistsStreamProvider);

    return playlists.when(
      data: (items) => ListView(
        children: [
          ListTile(
            leading: const Icon(Icons.add),
            title: const Text('Create playlist'),
            onTap: () => _createPlaylist(context, ref),
          ),
          if (items.isEmpty)
            const Padding(
              padding: EdgeInsets.all(32),
              child: Center(child: Text('No playlists yet.')),
            ),
          for (final playlist in items)
            ListTile(
              leading: Icon(
                playlist.isAutoGenerated
                    ? Icons.auto_awesome
                    : Icons.queue_music,
              ),
              title: Text(playlist.name),
              onTap: () => Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (_) => PlaylistDetailScreen(playlistId: playlist.id),
                ),
              ),
              trailing: playlist.isAutoGenerated
                  ? null
                  : PopupMenuButton<String>(
                      onSelected: (value) {
                        if (value == 'rename') {
                          _renamePlaylist(context, ref, playlist);
                        }
                        if (value == 'delete') {
                          ref
                              .read(playlistRepositoryProvider)
                              .deletePlaylist(playlist.id);
                        }
                      },
                      itemBuilder: (_) => const [
                        PopupMenuItem(value: 'rename', child: Text('Rename')),
                        PopupMenuItem(value: 'delete', child: Text('Delete')),
                      ],
                    ),
            ),
        ],
      ),
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, _) =>
          Center(child: Text('Failed to load playlists: $error')),
    );
  }

  Future<void> _createPlaylist(BuildContext context, WidgetRef ref) async {
    final name = await _promptForName(context, title: 'New playlist');
    if (name != null && name.isNotEmpty) {
      await ref.read(playlistRepositoryProvider).createPlaylist(name);
    }
  }

  Future<void> _renamePlaylist(
    BuildContext context,
    WidgetRef ref,
    Playlist playlist,
  ) async {
    final name = await _promptForName(
      context,
      title: 'Rename playlist',
      initialValue: playlist.name,
    );
    if (name != null && name.isNotEmpty) {
      await ref
          .read(playlistRepositoryProvider)
          .renamePlaylist(playlist.id, name);
    }
  }

  Future<String?> _promptForName(
    BuildContext context, {
    required String title,
    String initialValue = '',
  }) {
    final controller = TextEditingController(text: initialValue);
    return showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(title),
        content: TextField(
          controller: controller,
          autofocus: true,
          decoration: const InputDecoration(hintText: 'Playlist name'),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(controller.text.trim()),
            child: const Text('Save'),
          ),
        ],
      ),
    );
  }
}
