import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';

import '../../../data/models/playlist.dart';
import '../../../data/models/song.dart';
import '../../../data/repositories/playlist_repository.dart';
import '../../../shared/widgets/app_bar_icon_action.dart';
import '../../../shared/widgets/gradient_app_bar.dart';
import '../../../shared/widgets/mini_player.dart';
import '../../../shared/widgets/play_shuffle_header.dart';
import '../../../shared/widgets/song_list_tile.dart';
import '../../library/application/library_view_controller.dart';
import '../../library/presentation/library_view_sheet.dart';
import '../../playback/application/playback_controller.dart';
import '../../vibe_tagging/application/vibe_tagging_controller.dart';
import '../application/playlist_controller.dart';
import 'add_songs_sheet.dart';
import 'playlist_edit_dialog.dart';

/// View and manage the songs within a specific playlist (Screens.md #5),
/// with play/shuffle header actions and the same search, sort and filter
/// controls every other list has.
///
/// The playlist's own stored order is what shows until the user actually
/// picks a sort — see [LibraryView.sortChosen] — because arranging a playlist
/// by hand is the point of having one. Drag reordering (which edits that
/// stored order) is therefore only available while nothing is narrowing or
/// reordering the view.
class PlaylistDetailScreen extends ConsumerStatefulWidget {
  const PlaylistDetailScreen({super.key, required this.playlistId});

  final String playlistId;

  @override
  ConsumerState<PlaylistDetailScreen> createState() =>
      _PlaylistDetailScreenState();
}

class _PlaylistDetailScreenState extends ConsumerState<PlaylistDetailScreen> {
  /// Whether the list on screen is still the playlist's own order. Only then
  /// can a drag mean "move this song within the playlist".
  bool _isCustomView = false;

  @override
  Widget build(BuildContext context) {
    final detail = ref.watch(playlistDetailProvider(widget.playlistId));
    final playlist = detail.value?.playlist;
    final songs = detail.value?.songs ?? const <Song>[];
    final query = ref.watch(librarySearchQueryProvider);
    final view = ref.watch(libraryViewProvider);
    final vibeTagged = ref.watch(vibeTaggedSongIdsProvider);
    final vibeRestriction = ref.watch(libraryVibeCategoryRestrictionProvider);
    _isCustomView = query.trim().isNotEmpty || !view.isDefault;

    List<Song> visibleOf(List<Song> all) => applyLibraryView(
      all,
      query: query,
      view: view,
      vibeTaggedSongIds: vibeTagged,
      restrictToSongIds: vibeRestriction,
      preserveOrder: !view.sortChosen,
    );

    return Scaffold(
      bottomNavigationBar: const MiniPlayer(),
      appBar: GradientAppBar(
        title: Text(playlist?.name ?? 'Playlist'),
        actions: [
          AppBarIconAction(
            icon: const Icon(Icons.playlist_add),
            tooltip: 'Add songs',
            onPressed: () => AddSongsSheet.show(context, widget.playlistId),
          ),
          if (playlist != null) ...[
            AppBarIconAction(
              icon: const Icon(Icons.share_outlined),
              tooltip: 'Share',
              onPressed: () => _share(playlist, songs),
            ),
            if (!playlist.isAutoGenerated) ...[
              AppBarIconAction(
                icon: const Icon(Icons.edit_outlined),
                tooltip: 'Edit',
                onPressed: () => _editPlaylist(context, playlist),
              ),
              AppBarIconAction(
                icon: const Icon(Icons.delete_outline),
                tooltip: 'Delete',
                onPressed: () => _confirmDelete(context, playlist),
              ),
            ],
          ],
          const SizedBox(width: 4),
        ],
      ),
      body: detail.when(
        data: (value) {
          if (value == null) {
            return const Center(child: Text('Playlist not found.'));
          }
          final visible = visibleOf(value.songs);
          return CustomScrollView(
            slivers: [
              SliverToBoxAdapter(
                child: _PlaylistHeader(playlist: value.playlist),
              ),
              SliverToBoxAdapter(
                child: PlayShuffleHeader(
                  songs: value.songs,
                  sourcePlaylistId: widget.playlistId,
                ),
              ),
              const SliverToBoxAdapter(
                child: LibraryViewControls(hint: 'Search in playlist'),
              ),
              if (value.songs.isEmpty)
                const SliverToBoxAdapter(
                  child: Padding(
                    padding: EdgeInsets.all(32),
                    child: Center(
                      child: Text('No songs in this playlist yet.'),
                    ),
                  ),
                )
              else if (visible.isEmpty)
                const SliverToBoxAdapter(
                  child: Padding(
                    padding: EdgeInsets.all(32),
                    child: Center(child: Text('No songs match.')),
                  ),
                )
              else if (_isCustomView)
                SliverList.builder(
                  itemCount: visible.length,
                  itemBuilder: (context, index) => _songTile(visible, index),
                )
              else
                SliverReorderableList(
                  itemCount: visible.length,
                  onReorderItem: (oldIndex, newIndex) {
                    final reordered = [...value.songs];
                    final moved = reordered.removeAt(oldIndex);
                    reordered.insert(newIndex, moved);
                    ref
                        .read(playlistRepositoryProvider)
                        .reorderSongs(
                          widget.playlistId,
                          reordered.map((s) => s.id).toList(),
                        );
                  },
                  itemBuilder: (context, index) =>
                      ReorderableDelayedDragStartListener(
                        key: ValueKey(visible[index].id),
                        index: index,
                        child: _songTile(visible, index),
                      ),
                ),
            ],
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error, _) =>
            Center(child: Text('Failed to load playlist: $error')),
      ),
    );
  }

  Widget _songTile(List<Song> queue, int index) {
    final song = queue[index];
    return SongListTile(
      key: _isCustomView ? ValueKey(song.id) : null,
      song: song,
      onTap: () => ref
          .read(playbackControllerProvider.notifier)
          .playQueue(
            queue,
            startIndex: index,
            sourcePlaylistId: widget.playlistId,
          ),
      trailing: IconButton(
        icon: const Icon(Icons.remove_circle_outline),
        tooltip: 'Remove from playlist',
        onPressed: () => ref
            .read(playlistRepositoryProvider)
            .removeSong(widget.playlistId, song.id),
      ),
    );
  }

  Future<void> _share(Playlist playlist, List<Song> songs) async {
    final trackList = [
      for (final song in songs) '${song.title} — ${song.artist}',
    ].join('\n');
    await SharePlus.instance.share(
      ShareParams(
        text: songs.isEmpty ? playlist.name : '${playlist.name}\n\n$trackList',
      ),
    );
  }

  Future<void> _editPlaylist(BuildContext context, Playlist playlist) async {
    final result = await showPlaylistEditDialog(
      context,
      title: 'Edit playlist',
      initialValue: playlist.name,
      showCoverPicker: true,
      currentCoverPath: playlist.coverImagePath,
    );
    if (result == null) return;

    final repository = ref.read(playlistRepositoryProvider);
    if (result.name.isNotEmpty && result.name != playlist.name) {
      await repository.renamePlaylist(playlist.id, result.name);
    }
    if (result.coverImagePath != null) {
      await repository.setCoverImage(playlist.id, result.coverImagePath!);
    }
  }

  Future<void> _confirmDelete(BuildContext context, Playlist playlist) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Delete "${playlist.name}"?'),
        content: const Text(
          'This removes the playlist. Your songs stay in your library.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(true),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
    if (confirmed == true) {
      await ref.read(playlistRepositoryProvider).deletePlaylist(playlist.id);
      if (context.mounted) Navigator.of(context).pop();
    }
  }
}

class _PlaylistHeader extends StatelessWidget {
  const _PlaylistHeader({required this.playlist});

  final Playlist playlist;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final coverPath = playlist.coverImagePath;

    return Padding(
      padding: const EdgeInsets.all(24),
      child: Column(
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(20),
            child: coverPath != null
                ? Image.file(
                    File(coverPath),
                    width: 160,
                    height: 160,
                    fit: BoxFit.cover,
                  )
                : Container(
                    width: 160,
                    height: 160,
                    color: scheme.surfaceContainerHighest,
                    child: Icon(
                      playlist.isAutoGenerated
                          ? Icons.auto_awesome
                          : Icons.queue_music,
                      size: 56,
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
          ),
          const SizedBox(height: 16),
          Text(
            playlist.name,
            textAlign: TextAlign.center,
            style: Theme.of(context).textTheme.headlineSmall,
          ),
        ],
      ),
    );
  }
}
