import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../data/models/song.dart';
import '../../../data/repositories/playlist_repository.dart';
import '../application/playlist_controller.dart';

/// Lets the user save a single song into one or more playlists, creating a
/// new one inline if needed. The mirror image of [AddSongsSheet], which
/// picks songs for one already-open playlist.
class SaveToPlaylistSheet extends ConsumerWidget {
  const SaveToPlaylistSheet({super.key, required this.song});

  final Song song;

  static Future<void> show(BuildContext context, Song song) {
    return showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      builder: (_) => SaveToPlaylistSheet(song: song),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final playlists = ref.watch(playlistsStreamProvider);

    return DraggableScrollableSheet(
      expand: false,
      builder: (context, scrollController) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
              child: Text(
                'Save "${song.title}" to playlist',
                style: Theme.of(context).textTheme.titleMedium,
              ),
            ),
            ListTile(
              leading: const Icon(Icons.add),
              title: const Text('New playlist'),
              onTap: () => _createAndSave(context, ref),
            ),
            const Divider(height: 1),
            Flexible(
              child: playlists.when(
                data: (items) {
                  final manual = items
                      .where((playlist) => !playlist.isAutoGenerated)
                      .toList();
                  if (manual.isEmpty) {
                    return const Padding(
                      padding: EdgeInsets.all(32),
                      child: Center(child: Text('No playlists yet.')),
                    );
                  }
                  return ListView.builder(
                    controller: scrollController,
                    shrinkWrap: true,
                    itemCount: manual.length,
                    itemBuilder: (context, index) {
                      final playlist = manual[index];
                      return ListTile(
                        leading: const Icon(Icons.queue_music),
                        title: Text(playlist.name),
                        onTap: () => _save(context, ref, playlist.id),
                      );
                    },
                  );
                },
                loading: () => const Center(child: CircularProgressIndicator()),
                error: (error, _) =>
                    Center(child: Text('Failed to load playlists: $error')),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _save(
    BuildContext context,
    WidgetRef ref,
    String playlistId,
  ) async {
    await ref.read(playlistRepositoryProvider).addSong(playlistId, song.id);
    if (!context.mounted) return;
    Navigator.of(context).pop();
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Added to playlist')),
    );
  }

  Future<void> _createAndSave(BuildContext context, WidgetRef ref) async {
    final name = await _promptForName(context);
    if (name == null || name.isEmpty) return;
    final playlist = await ref
        .read(playlistRepositoryProvider)
        .createPlaylist(name);
    if (!context.mounted) return;
    await _save(context, ref, playlist.id);
  }

  Future<String?> _promptForName(BuildContext context) {
    final controller = TextEditingController();
    return showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('New playlist'),
        content: TextField(
          controller: controller,
          autofocus: true,
          decoration: const InputDecoration(hintText: 'Playlist name'),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(controller.text.trim()),
            child: const Text('Save'),
          ),
        ],
      ),
    );
  }
}
