import 'dart:io';

import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';

import '../datasources/app_database.dart';
import '../models/playlist.dart';
import '../models/song.dart';

/// Single access point for user-created and auto-generated playlists.
class PlaylistRepository {
  PlaylistRepository({required this._database});

  final AppDatabase _database;
  static const _uuid = Uuid();

  Stream<List<Playlist>> watchPlaylists() {
    final query = _database.select(_database.playlists)
      ..orderBy([(t) => OrderingTerm.desc(t.createdAt)]);
    return query.watch().map(
      (rows) => rows.map(Playlist.fromRow).toList(growable: false),
    );
  }

  /// Emits `null` if the playlist has been deleted.
  Stream<PlaylistWithSongs?> watchPlaylistWithSongs(String playlistId) {
    final query = _database.select(_database.playlists)
      ..where((t) => t.id.equals(playlistId));

    return query.watchSingleOrNull().asyncMap((row) async {
      if (row == null) return null;
      final songs = await _songsForPlaylist(playlistId);
      return PlaylistWithSongs(playlist: Playlist.fromRow(row), songs: songs);
    });
  }

  Future<Playlist> createPlaylist(String name) async {
    final id = _uuid.v4();
    final createdAt = DateTime.now();
    await _database
        .into(_database.playlists)
        .insert(
          PlaylistsCompanion.insert(id: id, name: name, createdAt: createdAt),
        );
    return Playlist(
      id: id,
      name: name,
      isAutoGenerated: false,
      createdAt: createdAt,
    );
  }

  Future<void> renamePlaylist(String playlistId, String newName) {
    return (_database.update(_database.playlists)
          ..where((t) => t.id.equals(playlistId)))
        .write(PlaylistsCompanion(name: Value(newName)));
  }

  Future<void> deletePlaylist(String playlistId) async {
    final row = await (_database.select(
      _database.playlists,
    )..where((t) => t.id.equals(playlistId))).getSingleOrNull();

    await (_database.delete(
      _database.playlists,
    )..where((t) => t.id.equals(playlistId))).go();

    final coverPath = row?.coverImagePath;
    if (coverPath != null) {
      final coverFile = File(coverPath);
      if (await coverFile.exists()) await coverFile.delete();
    }
  }

  /// Copies [sourceImagePath] (e.g. from an image picker, whose path can be
  /// revoked by the OS) into a durable app-owned directory and stores that
  /// stable path as the playlist's cover — mirrors the pattern
  /// `BackupRepository` uses for backup files.
  Future<void> setCoverImage(String playlistId, String sourceImagePath) async {
    final coversDir = await _coversDirectory();
    // Clear out any previous cover for this playlist first — the extension
    // may differ from the new one, so a plain overwrite wouldn't remove it.
    await for (final entity in coversDir.list()) {
      if (entity is File && p.basenameWithoutExtension(entity.path) == playlistId) {
        await entity.delete();
      }
    }

    final extension = p.extension(sourceImagePath);
    final destination = File(p.join(coversDir.path, '$playlistId$extension'));
    await File(sourceImagePath).copy(destination.path);

    await (_database.update(_database.playlists)
          ..where((t) => t.id.equals(playlistId)))
        .write(PlaylistsCompanion(coverImagePath: Value(destination.path)));
  }

  Future<Directory> _coversDirectory() async {
    final documentsDir = await getApplicationDocumentsDirectory();
    final coversDir = Directory(p.join(documentsDir.path, 'playlist_covers'));
    await coversDir.create(recursive: true);
    return coversDir;
  }

  Future<void> addSong(String playlistId, String songId) async {
    final nextPosition = await _nextPosition(playlistId);
    await _database
        .into(_database.playlistSongs)
        .insert(
          PlaylistSongsCompanion.insert(
            playlistId: playlistId,
            songId: songId,
            position: nextPosition,
          ),
          mode: InsertMode.insertOrIgnore,
        );
  }

  Future<void> removeSong(String playlistId, String songId) {
    return (_database.delete(_database.playlistSongs)..where(
          (t) => t.playlistId.equals(playlistId) & t.songId.equals(songId),
        ))
        .go();
  }

  /// Persists a full reorder: [orderedSongIds] must contain every song
  /// currently in the playlist, in its new order.
  Future<void> reorderSongs(String playlistId, List<String> orderedSongIds) {
    return _database.batch((batch) {
      for (var i = 0; i < orderedSongIds.length; i++) {
        batch.update(
          _database.playlistSongs,
          PlaylistSongsCompanion(position: Value(i)),
          where: (t) =>
              t.playlistId.equals(playlistId) &
              t.songId.equals(orderedSongIds[i]),
        );
      }
    });
  }

  /// Removes the auto-generated playlist tied to [sourceMoodTagId], if any.
  ///
  /// Call this *before* deleting the mood tag itself — the tag's `onDelete:
  /// setNull` foreign key would otherwise clear `sourceMoodTagId` first,
  /// making the orphaned playlist impossible to find afterward.
  Future<void> deleteAutoPlaylistForMoodTag(String sourceMoodTagId) async {
    final existing =
        await (_database.select(_database.playlists)
              ..where((t) => t.sourceMoodTagId.equals(sourceMoodTagId)))
            .getSingleOrNull();
    if (existing != null) {
      await (_database.delete(
        _database.playlists,
      )..where((t) => t.id.equals(existing.id))).go();
    }
  }

  /// Replaces an auto-generated playlist's membership to match [songIds]
  /// exactly, creating the playlist if needed and removing it if [songIds]
  /// is empty (SRS F-4.2: auto-generated mood playlists).
  Future<void> replaceAutoPlaylistSongs({
    required String sourceMoodTagId,
    required String name,
    required List<String> songIds,
  }) async {
    await _database.transaction(() async {
      final existing =
          await (_database.select(_database.playlists)
                ..where((t) => t.sourceMoodTagId.equals(sourceMoodTagId)))
              .getSingleOrNull();

      if (existing == null && songIds.isEmpty) {
        return;
      }

      if (existing != null && songIds.isEmpty) {
        // No songs left with this tag: drop the auto playlist entirely
        // (playlist_songs cascade-deletes with it).
        await (_database.delete(
          _database.playlists,
        )..where((t) => t.id.equals(existing.id))).go();
        return;
      }

      final playlistId = existing?.id ?? _uuid.v4();
      if (existing == null) {
        await _database
            .into(_database.playlists)
            .insert(
              PlaylistsCompanion.insert(
                id: playlistId,
                name: name,
                createdAt: DateTime.now(),
                isAutoGenerated: const Value(true),
                sourceMoodTagId: Value(sourceMoodTagId),
              ),
            );
      } else {
        await (_database.update(_database.playlists)
              ..where((t) => t.id.equals(playlistId)))
            .write(PlaylistsCompanion(name: Value(name)));
      }

      await (_database.delete(
        _database.playlistSongs,
      )..where((t) => t.playlistId.equals(playlistId))).go();

      await _database.batch((batch) {
        batch.insertAll(_database.playlistSongs, [
          for (var i = 0; i < songIds.length; i++)
            PlaylistSongsCompanion.insert(
              playlistId: playlistId,
              songId: songIds[i],
              position: i,
            ),
        ]);
      });
    });
  }

  /// One-off (non-reactive) fetch of manually created playlists (excludes
  /// auto-generated mood playlists, which regenerate themselves), used by
  /// `BackupRepository`.
  Future<List<PlaylistWithSongs>> allManualPlaylistsWithSongs() async {
    final query = _database.select(_database.playlists)
      ..where((t) => t.isAutoGenerated.equals(false));
    final rows = await query.get();

    final result = <PlaylistWithSongs>[];
    for (final row in rows) {
      final songs = await _songsForPlaylist(row.id);
      result.add(
        PlaylistWithSongs(playlist: Playlist.fromRow(row), songs: songs),
      );
    }
    return result;
  }

  Future<int> _nextPosition(String playlistId) async {
    final maxPosition = _database.playlistSongs.position.max();
    final query = _database.selectOnly(_database.playlistSongs)
      ..addColumns([maxPosition])
      ..where(_database.playlistSongs.playlistId.equals(playlistId));
    final row = await query.getSingleOrNull();
    return (row?.read(maxPosition) ?? -1) + 1;
  }

  Future<List<Song>> _songsForPlaylist(String playlistId) async {
    final query =
        _database.select(_database.playlistSongs).join([
            innerJoin(
              _database.songs,
              _database.songs.id.equalsExp(_database.playlistSongs.songId),
            ),
          ])
          ..where(_database.playlistSongs.playlistId.equals(playlistId))
          ..orderBy([OrderingTerm.asc(_database.playlistSongs.position)]);

    final rows = await query.get();
    return rows
        .map((row) => Song.fromRow(row.readTable(_database.songs)))
        .toList(growable: false);
  }
}

final playlistRepositoryProvider = Provider<PlaylistRepository>(
  (ref) => PlaylistRepository(database: ref.watch(appDatabaseProvider)),
);
