import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

import '../datasources/app_database.dart';
import '../models/playlist.dart';
import '../models/song.dart';

/// Single access point for user-created and auto-generated playlists.
class PlaylistRepository {
  PlaylistRepository({required this._database});

  final AppDatabase _database;
  static const _uuid = Uuid();

  Stream<List<Playlist>> watchPlaylists() {
    final query = _database.select(_database.playlists)
      ..orderBy([(t) => OrderingTerm.desc(t.createdAt)]);
    return query.watch().map(
      (rows) => rows.map(Playlist.fromRow).toList(growable: false),
    );
  }

  /// Emits `null` if the playlist has been deleted.
  Stream<PlaylistWithSongs?> watchPlaylistWithSongs(String playlistId) {
    final query = _database.select(_database.playlists)
      ..where((t) => t.id.equals(playlistId));

    return query.watchSingleOrNull().asyncMap((row) async {
      if (row == null) return null;
      final songs = await _songsForPlaylist(playlistId);
      return PlaylistWithSongs(playlist: Playlist.fromRow(row), songs: songs);
    });
  }

  Future<Playlist> createPlaylist(String name) async {
    final id = _uuid.v4();
    final createdAt = DateTime.now();
    await _database
        .into(_database.playlists)
        .insert(
          PlaylistsCompanion.insert(id: id, name: name, createdAt: createdAt),
        );
    return Playlist(
      id: id,
      name: name,
      isAutoGenerated: false,
      createdAt: createdAt,
    );
  }

  Future<void> renamePlaylist(String playlistId, String newName) {
    return (_database.update(_database.playlists)
          ..where((t) => t.id.equals(playlistId)))
        .write(PlaylistsCompanion(name: Value(newName)));
  }

  Future<void> deletePlaylist(String playlistId) {
    return (_database.delete(
      _database.playlists,
    )..where((t) => t.id.equals(playlistId))).go();
  }

  Future<void> addSong(String playlistId, String songId) async {
    final nextPosition = await _nextPosition(playlistId);
    await _database
        .into(_database.playlistSongs)
        .insert(
          PlaylistSongsCompanion.insert(
            playlistId: playlistId,
            songId: songId,
            position: nextPosition,
          ),
          mode: InsertMode.insertOrIgnore,
        );
  }

  Future<void> removeSong(String playlistId, String songId) {
    return (_database.delete(_database.playlistSongs)..where(
          (t) => t.playlistId.equals(playlistId) & t.songId.equals(songId),
        ))
        .go();
  }

  /// Persists a full reorder: [orderedSongIds] must contain every song
  /// currently in the playlist, in its new order.
  Future<void> reorderSongs(String playlistId, List<String> orderedSongIds) {
    return _database.batch((batch) {
      for (var i = 0; i < orderedSongIds.length; i++) {
        batch.update(
          _database.playlistSongs,
          PlaylistSongsCompanion(position: Value(i)),
          where: (t) =>
              t.playlistId.equals(playlistId) &
              t.songId.equals(orderedSongIds[i]),
        );
      }
    });
  }

  Future<int> _nextPosition(String playlistId) async {
    final maxPosition = _database.playlistSongs.position.max();
    final query = _database.selectOnly(_database.playlistSongs)
      ..addColumns([maxPosition])
      ..where(_database.playlistSongs.playlistId.equals(playlistId));
    final row = await query.getSingleOrNull();
    return (row?.read(maxPosition) ?? -1) + 1;
  }

  Future<List<Song>> _songsForPlaylist(String playlistId) async {
    final query =
        _database.select(_database.playlistSongs).join([
            innerJoin(
              _database.songs,
              _database.songs.id.equalsExp(_database.playlistSongs.songId),
            ),
          ])
          ..where(_database.playlistSongs.playlistId.equals(playlistId))
          ..orderBy([OrderingTerm.asc(_database.playlistSongs.position)]);

    final rows = await query.get();
    return rows
        .map((row) => Song.fromRow(row.readTable(_database.songs)))
        .toList(growable: false);
  }
}

final playlistRepositoryProvider = Provider<PlaylistRepository>(
  (ref) => PlaylistRepository(database: ref.watch(appDatabaseProvider)),
);
