import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

part 'app_database.g.dart';

/// Preset mood/energy label a song can be tagged with (SRS F-2.6).
@DataClassName('MoodTagRow')
class MoodTags extends Table {
  TextColumn get id => text()();
  TextColumn get label => text()();
  TextColumn get colorHex => text()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Cached local-library metadata, keyed by the device media store ID.
///
/// Caching avoids a full device re-scan on every launch (SRS N-3); the
/// library controller refreshes this incrementally instead.
@DataClassName('SongRow')
class Songs extends Table {
  TextColumn get id => text()();
  TextColumn get filePath => text()();
  TextColumn get title => text()();
  TextColumn get artist => text()();
  TextColumn get album => text()();
  IntColumn get durationMs => integer()();
  TextColumn get moodTagId => text().nullable().references(
    MoodTags,
    #id,
    onDelete: KeyAction.setNull,
  )();
  BoolColumn get isLiked => boolean().withDefault(const Constant(false))();
  BoolColumn get isMissing => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}

/// A user-created or auto-generated collection of songs.
@DataClassName('PlaylistRow')
class Playlists extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  BoolColumn get isAutoGenerated =>
      boolean().withDefault(const Constant(false))();
  TextColumn get sourceMoodTagId => text().nullable().references(
    MoodTags,
    #id,
    onDelete: KeyAction.setNull,
  )();
  DateTimeColumn get createdAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Join entity between [Playlists] and [Songs], preserving manual ordering.
@DataClassName('PlaylistSongRow')
class PlaylistSongs extends Table {
  TextColumn get playlistId =>
      text().references(Playlists, #id, onDelete: KeyAction.cascade)();
  TextColumn get songId =>
      text().references(Songs, #id, onDelete: KeyAction.cascade)();
  IntColumn get position => integer()();

  @override
  Set<Column> get primaryKey => {playlistId, songId};
}

/// Single-row app configuration. [id] is always [Settings.singletonId].
@DataClassName('SettingsRow')
class Settings extends Table {
  static const singletonId = 'default';

  TextColumn get id => text()();
  BoolColumn get adaptiveDarkModeEnabled =>
      boolean().withDefault(const Constant(true))();
  TextColumn get manualThemeOverride => text().nullable()();
  TextColumn get themeSeedColorHex =>
      text().withDefault(const Constant('#673AB7'))();
  TextColumn get visualizerColorHex =>
      text().withDefault(const Constant('#673AB7'))();
  BoolColumn get crossfadeEnabled =>
      boolean().withDefault(const Constant(false))();
  IntColumn get crossfadeDurationMs =>
      integer().withDefault(const Constant(3000))();

  @override
  Set<Column> get primaryKey => {id};
}

@DriftDatabase(tables: [MoodTags, Songs, Playlists, PlaylistSongs, Settings])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Used to inject an in-memory executor for tests.
  AppDatabase.connect(super.executor);

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) => m.createAll(),
    onUpgrade: (m, from, to) async {
      if (from < 2) {
        await m.createTable(moodTags);
        await m.createTable(playlists);
        await m.createTable(playlistSongs);
        await m.createTable(settings);
      }
      if (from < 3) {
        await m.addColumn(settings, settings.themeSeedColorHex);
        await m.addColumn(settings, settings.visualizerColorHex);
        await m.addColumn(settings, settings.crossfadeEnabled);
        await m.addColumn(settings, settings.crossfadeDurationMs);
      }
    },
  );

  static QueryExecutor _openConnection() => driftDatabase(name: 'zivybb');
}

final appDatabaseProvider = Provider<AppDatabase>((ref) {
  final database = AppDatabase();
  ref.onDispose(database.close);
  return database;
});
