import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

part 'app_database.g.dart';

// Every table below that references another one also spells its foreign key
// out in `customConstraints`. That is not belt-and-braces: the bundled
// `drift_dev` cannot resolve the table argument of a `.references()` call
// against the analyzer version the Flutter SDK pins ("This parameter should
// be a simple class name"), and silently emits no `REFERENCES` clause at
// all — so every `onDelete:` here was dead code until the explicit
// constraints were added. The `.references(...)` calls are kept because
// drift still uses them to order `createAll` and they document intent at the
// column.
//
// This only fixes databases created from here on: SQLite cannot add a
// foreign key to an existing table, so installs predating this keep
// unconstrained tables. Every repository that deletes a referenced row
// therefore cleans up its own dependents rather than trusting the database
// to cascade.

/// A mood/energy label a song can be tagged with (SRS F-2.6). Starts out
/// with a handful of built-in presets, but is fully user-manageable.
@DataClassName('MoodTagRow')
class MoodTags extends Table {
  TextColumn get id => text()();
  TextColumn get label => text()();
  TextColumn get colorHex => text()();
  IntColumn get sortOrder => integer().withDefault(const Constant(0))();

  @override
  Set<Column> get primaryKey => {id};
}

/// Cached local-library metadata, keyed by the device media store ID.
///
/// Caching avoids a full device re-scan on every launch (SRS N-3); the
/// library controller refreshes this incrementally instead.
@DataClassName('SongRow')
class Songs extends Table {
  TextColumn get id => text()();
  TextColumn get filePath => text()();
  TextColumn get title => text()();
  TextColumn get artist => text()();
  TextColumn get album => text()();
  IntColumn get durationMs => integer()();
  TextColumn get moodTagId => text().nullable().references(
    MoodTags,
    #id,
    onDelete: KeyAction.setNull,
  )();
  BoolColumn get isLiked => boolean().withDefault(const Constant(false))();
  BoolColumn get isMissing => boolean().withDefault(const Constant(false))();
  IntColumn get playCount => integer().withDefault(const Constant(0))();
  DateTimeColumn get lastPlayedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (mood_tag_id) REFERENCES mood_tags (id) ON DELETE SET NULL',
  ];
}

/// A user-created or auto-generated collection of songs.
@DataClassName('PlaylistRow')
class Playlists extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  BoolColumn get isAutoGenerated =>
      boolean().withDefault(const Constant(false))();
  TextColumn get sourceMoodTagId => text().nullable().references(
    MoodTags,
    #id,
    onDelete: KeyAction.setNull,
  )();
  DateTimeColumn get createdAt => dateTime()();
  TextColumn get coverImagePath => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (source_mood_tag_id) REFERENCES mood_tags (id) '
        'ON DELETE SET NULL',
  ];
}

/// Join entity between [Playlists] and [Songs], preserving manual ordering.
@DataClassName('PlaylistSongRow')
class PlaylistSongs extends Table {
  TextColumn get playlistId =>
      text().references(Playlists, #id, onDelete: KeyAction.cascade)();
  TextColumn get songId =>
      text().references(Songs, #id, onDelete: KeyAction.cascade)();
  IntColumn get position => integer()();

  @override
  Set<Column> get primaryKey => {playlistId, songId};

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE',
    'FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE',
  ];
}

/// A named set of equalizer band gains the user can select (SRS F-1.6).
@DataClassName('EqualizerPresetRow')
class EqualizerPresets extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();

  /// JSON-encoded `List<double>` of gains in decibels, one per band.
  TextColumn get bandLevelsJson => text()();

  @override
  Set<Column> get primaryKey => {id};
}

/// A backup snapshot's metadata; the snapshot itself is a JSON file at
/// [filePath] (Entity-Diagrams-UML.md BACKUP).
@DataClassName('BackupRow')
class Backups extends Table {
  TextColumn get id => text()();
  DateTimeColumn get createdAt => dateTime()();
  TextColumn get filePath => text()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Single-row snapshot of what was playing when the app was last closed, so
/// launching it can pick up where the user left off.
///
/// Deliberately separate from [Settings]: this is transient session state,
/// not configuration, and it is intentionally left out of backups — restoring
/// a months-old backup should not yank the user back to whatever track was
/// playing when it was taken.
@DataClassName('PlaybackSessionRow')
class PlaybackSessions extends Table {
  static const singletonId = 'default';

  TextColumn get id => text()();

  /// JSON-encoded `List<String>` of song IDs, in queue order.
  TextColumn get songIdsJson => text().withDefault(const Constant('[]'))();
  IntColumn get currentIndex => integer().withDefault(const Constant(0))();
  IntColumn get positionMs => integer().withDefault(const Constant(0))();
  BoolColumn get shuffleEnabled =>
      boolean().withDefault(const Constant(false))();
  TextColumn get repeatMode => text().withDefault(const Constant('off'))();
  RealColumn get speed => real().withDefault(const Constant(1.0))();
  TextColumn get sourcePlaylistId => text().nullable().references(
    Playlists,
    #id,
    onDelete: KeyAction.setNull,
  )();

  @override
  Set<Column> get primaryKey => {id};

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (source_playlist_id) REFERENCES playlists (id) '
        'ON DELETE SET NULL',
  ];
}

/// Single-row app configuration. [id] is always [Settings.singletonId].
@DataClassName('SettingsRow')
class Settings extends Table {
  static const singletonId = 'default';

  TextColumn get id => text()();
  BoolColumn get adaptiveDarkModeEnabled =>
      boolean().withDefault(const Constant(true))();
  TextColumn get manualThemeOverride => text().nullable()();
  TextColumn get themeSeedColorHex =>
      text().withDefault(const Constant('#673AB7'))();
  TextColumn get visualizerColorHex =>
      text().withDefault(const Constant('#673AB7'))();
  BoolColumn get crossfadeEnabled =>
      boolean().withDefault(const Constant(false))();
  IntColumn get crossfadeDurationMs =>
      integer().withDefault(const Constant(3000))();
  TextColumn get currentEqualizerPresetId => text().nullable().references(
    EqualizerPresets,
    #id,
    onDelete: KeyAction.setNull,
  )();
  TextColumn get visualizerStyle =>
      text().withDefault(const Constant('bars'))();
  BoolColumn get showAlbumArtInMiniPlayer =>
      boolean().withDefault(const Constant(true))();
  BoolColumn get showVisualizerInMiniPlayer =>
      boolean().withDefault(const Constant(false))();
  BoolColumn get showAlbumArtInNowPlaying =>
      boolean().withDefault(const Constant(true))();
  BoolColumn get showVisualizerInNowPlaying =>
      boolean().withDefault(const Constant(true))();

  /// Opt-in: drive the visualizer from the real audio signal rather than the
  /// simulated waveform. Off by default because it needs RECORD_AUDIO.
  BoolColumn get realVisualizerEnabled =>
      boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (current_equalizer_preset_id) REFERENCES '
        'equalizer_presets (id) ON DELETE SET NULL',
  ];
}

@DriftDatabase(
  tables: [
    MoodTags,
    Songs,
    Playlists,
    PlaylistSongs,
    Settings,
    EqualizerPresets,
    Backups,
    PlaybackSessions,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Used to inject an in-memory executor for tests.
  AppDatabase.connect(super.executor);

  @override
  int get schemaVersion => 9;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) => m.createAll(),
    onUpgrade: (m, from, to) async {
      if (from < 2) {
        await m.createTable(moodTags);
        await m.createTable(playlists);
        await m.createTable(playlistSongs);
        await m.createTable(settings);
      }
      if (from < 3) {
        await m.addColumn(settings, settings.themeSeedColorHex);
        await m.addColumn(settings, settings.visualizerColorHex);
        await m.addColumn(settings, settings.crossfadeEnabled);
        await m.addColumn(settings, settings.crossfadeDurationMs);
      }
      if (from < 4) {
        await m.createTable(equalizerPresets);
        await m.createTable(backups);
        await m.addColumn(settings, settings.currentEqualizerPresetId);
      }
      if (from < 5) {
        await m.addColumn(moodTags, moodTags.sortOrder);
        await m.addColumn(settings, settings.visualizerStyle);
      }
      if (from < 6) {
        await m.addColumn(playlists, playlists.coverImagePath);
        await m.addColumn(settings, settings.showAlbumArtInMiniPlayer);
        await m.addColumn(settings, settings.showVisualizerInMiniPlayer);
        await m.addColumn(settings, settings.showAlbumArtInNowPlaying);
        await m.addColumn(settings, settings.showVisualizerInNowPlaying);
        await m.addColumn(songs, songs.playCount);
        await m.addColumn(songs, songs.lastPlayedAt);
      }
      if (from < 7) {
        // Some devices reached user_version 6 before the songs.playCount /
        // songs.lastPlayedAt addColumn calls above existed, so the `from < 6`
        // block above never (and will never again) add them for those
        // devices. Add whichever of the two are still actually missing.
        if (!await _hasColumn(m, 'songs', 'play_count')) {
          await m.addColumn(songs, songs.playCount);
        }
        if (!await _hasColumn(m, 'songs', 'last_played_at')) {
          await m.addColumn(songs, songs.lastPlayedAt);
        }
      }
      if (from < 8) {
        await m.createTable(playbackSessions);
        await _purgeOrphanedRows();
      }
      if (from < 9) {
        await m.addColumn(settings, settings.realVisualizerEnabled);
      }
    },
    beforeOpen: (details) async {
      // SQLite enforces foreign keys only when this pragma is on, and it
      // defaults to *off* — every `onDelete:` in the table definitions above
      // was silently inert until this was added. Without it, deleting a
      // playlist left its playlist_songs rows behind, and deleting a mood tag
      // left songs pointing at a tag that no longer existed (which resurfaced
      // as phantom tags once the built-in presets were re-seeded under their
      // fixed IDs). It has to be set per connection, not once at creation.
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );

  /// Clears rows left dangling by the years the foreign keys weren't being
  /// enforced. Turning the pragma on doesn't retroactively validate existing
  /// data, so without this the old orphans would linger indefinitely.
  Future<void> _purgeOrphanedRows() async {
    await customStatement(
      'DELETE FROM playlist_songs WHERE playlist_id NOT IN '
      '(SELECT id FROM playlists) OR song_id NOT IN (SELECT id FROM songs)',
    );
    await customStatement(
      'UPDATE songs SET mood_tag_id = NULL WHERE mood_tag_id IS NOT NULL '
      'AND mood_tag_id NOT IN (SELECT id FROM mood_tags)',
    );
    await customStatement(
      'UPDATE playlists SET source_mood_tag_id = NULL '
      'WHERE source_mood_tag_id IS NOT NULL AND source_mood_tag_id NOT IN '
      '(SELECT id FROM mood_tags)',
    );
    await customStatement(
      'UPDATE settings SET current_equalizer_preset_id = NULL '
      'WHERE current_equalizer_preset_id IS NOT NULL AND '
      'current_equalizer_preset_id NOT IN (SELECT id FROM equalizer_presets)',
    );
  }

  static Future<bool> _hasColumn(
    Migrator m,
    String table,
    String column,
  ) async {
    final row = await m.database
        .customSelect(
          "SELECT 1 FROM pragma_table_info('$table') WHERE name = ?",
          variables: [Variable.withString(column)],
        )
        .getSingleOrNull();
    return row != null;
  }

  static QueryExecutor _openConnection() => driftDatabase(name: 'zivybb');
}

final appDatabaseProvider = Provider<AppDatabase>((ref) {
  final database = AppDatabase();
  ref.onDispose(database.close);
  return database;
});
