import 'package:flutter/foundation.dart';

import '../datasources/app_database.dart';
import 'song.dart';

/// A user-created or auto-generated collection of songs.
@immutable
class Playlist {
  const Playlist({
    required this.id,
    required this.name,
    required this.isAutoGenerated,
    required this.createdAt,
    this.sourceMoodTagId,
    this.coverImagePath,
  });

  factory Playlist.fromRow(PlaylistRow row) {
    return Playlist(
      id: row.id,
      name: row.name,
      isAutoGenerated: row.isAutoGenerated,
      createdAt: row.createdAt,
      sourceMoodTagId: row.sourceMoodTagId,
      coverImagePath: row.coverImagePath,
    );
  }

  final String id;
  final String name;
  final bool isAutoGenerated;
  final DateTime createdAt;
  final String? sourceMoodTagId;
  final String? coverImagePath;

  @override
  bool operator ==(Object other) => other is Playlist && other.id == id;

  @override
  int get hashCode => id.hashCode;
}

/// A playlist together with its ordered songs.
@immutable
class PlaylistWithSongs {
  const PlaylistWithSongs({required this.playlist, required this.songs});

  final Playlist playlist;
  final List<Song> songs;
}
