#!/usr/bin/env python3
"""Rasterize the Zivybb mark into the PNGs Android needs.

The mark is a calligraphic ZV monogram: one looping stroke draws the Z and
threads through a second stroke that sweeps the V, so the two interlace like
a ribbon. Both are brush strokes — the outline is generated by offsetting a
Bezier centreline by a width that varies along its length, which is what
gives the thick/thin calligraphic weight rather than a uniform pen line.

The same geometry lives in `lib/shared/widgets/zivybb_logo.dart` (for
drawing in-app) and `assets/images/zivybb_logo.svg` (as the design source).
Edit one and edit the others.

Nothing in the build runs this; it is a one-shot generator kept in the repo
so the icons can be regenerated from source rather than being opaque
binaries. Requires numpy + Pillow::

    python3 tools/zivybb_logo.py
"""

from __future__ import annotations

import os

import numpy as np
from PIL import Image, ImageDraw

# --- Design space -------------------------------------------------------
CANVAS = 512.0
CORNER_RADIUS = 114.0

# Cubic Bezier centrelines, as [start, control1, control2, end] in the
# 512x512 design space.
#
# The Z: a flattened loop drawn left to right along the bottom, up and back
# over the top, then down across its own bottom stroke and away into a
# descending tail.
STROKE_Z = [
    [(106, 216), (160, 242), (232, 248), (290, 234)],
    [(290, 234), (336, 220), (332, 158), (278, 146)],
    [(278, 146), (232, 134), (196, 150), (188, 182)],
    [(188, 182), (182, 218), (204, 252), (230, 278)],
    [(230, 278), (248, 314), (232, 366), (200, 402)],
]
# The V, split at its turn. Offsetting a single centreline through a corner
# that sharp folds the inner edge over itself and fills the notch in; two
# strokes tapering to a shared point give a clean apex instead.
STROKE_V_DOWN = [[(242, 112), (258, 180), (290, 270), (320, 362)]]
STROKE_V_UP = [[(320, 362), (346, 298), (380, 204), (404, 110)]]

# Stroke width along the centreline, as (t, width) with t spanning the whole
# stroke. Swells on the downstrokes and pinches at turns and ends, the way a
# brush loaded on entry and lifted on exit would.
WIDTH_Z = [
    (0.0, 10), (0.14, 30), (0.32, 24), (0.5, 19), (0.64, 22), (0.82, 32), (1.0, 8)
]
WIDTH_V_DOWN = [(0.0, 9), (0.3, 26), (0.6, 36), (0.85, 24), (1.0, 9)]
WIDTH_V_UP = [(0.0, 9), (0.25, 22), (0.5, 20), (0.8, 12), (1.0, 7)]

# The Z's bottom stroke is redrawn last so it passes *over* the V there,
# having passed under it higher up — that alternation is the weave.
Z_OVER_RANGE = (0.0, 0.21)

# Width of the transparent gap punched around a stroke where it crosses over
# another, so the overlap reads as one passing in front of the other.
WEAVE_GAP = 11.0

STROKE_GRADIENT_START = (105.0, 110.0)
STROKE_GRADIENT_END = (405.0, 400.0)
STROKE_STOPS = [
    (0.00, (0x22, 0xD3, 0xEE)),
    (0.45, (0x8B, 0x5C, 0xF6)),
    (1.00, (0xF4, 0x3F, 0x8E)),
]

BACKDROP_TOP = (0x1A, 0x17, 0x30)
BACKDROP_BOTTOM = (0x0E, 0x0C, 0x18)

SUPERSAMPLE = 4
SAMPLES_PER_SEGMENT = 96


# --- Curve maths --------------------------------------------------------
def _cubic(seg, t):
    (x0, y0), (x1, y1), (x2, y2), (x3, y3) = seg
    u = 1 - t
    a, b, c, d = u * u * u, 3 * u * u * t, 3 * u * t * t, t * t * t
    return (a * x0 + b * x1 + c * x2 + d * x3,
            a * y0 + b * y1 + c * y2 + d * y3)


def _cubic_tangent(seg, t):
    (x0, y0), (x1, y1), (x2, y2), (x3, y3) = seg
    u = 1 - t
    a, b, c = 3 * u * u, 6 * u * t, 3 * t * t
    return (a * (x1 - x0) + b * (x2 - x1) + c * (x3 - x2),
            a * (y1 - y0) + b * (y2 - y1) + c * (y3 - y2))


def _width_at(profile, t):
    if t <= profile[0][0]:
        return profile[0][1]
    for (t0, w0), (t1, w1) in zip(profile, profile[1:]):
        if t <= t1:
            return w0 + (w1 - w0) * (t - t0) / (t1 - t0)
    return profile[-1][1]


def stroke_outline(segments, profile, *, t_range=(0.0, 1.0), grow=0.0):
    """Closed polygon tracing a variable-width stroke.

    Walks the centreline sampling position and tangent, offsets by half the
    local width along the normal to collect one side, then returns down the
    other — so the result can simply be filled.

    `grow` widens the whole stroke uniformly, which is how the knockout used
    for the weave gap is produced.
    """
    left, right = [], []
    total = len(segments)
    for index, segment in enumerate(segments):
        for step in range(SAMPLES_PER_SEGMENT + 1):
            local = step / SAMPLES_PER_SEGMENT
            t = (index + local) / total
            if not (t_range[0] <= t <= t_range[1]):
                continue
            x, y = _cubic(segment, local)
            dx, dy = _cubic_tangent(segment, local)
            length = max((dx * dx + dy * dy) ** 0.5, 1e-6)
            # Normal is the tangent rotated a quarter turn.
            nx, ny = -dy / length, dx / length
            half = (_width_at(profile, t) + grow) / 2
            left.append((x + nx * half, y + ny * half))
            right.append((x - nx * half, y - ny * half))
    return left + right[::-1]


# --- Rasterizing --------------------------------------------------------
def _polygon_coverage(polygon, size, scale=1.0):
    """Antialiased 0..1 coverage mask, by filling at SUPERSAMPLE and averaging."""
    n = size * SUPERSAMPLE
    centre = CANVAS / 2.0
    points = [
        (((x - centre) * scale + centre) * n / CANVAS,
         ((y - centre) * scale + centre) * n / CANVAS)
        for x, y in polygon
    ]
    mask = Image.new("L", (n, n), 0)
    ImageDraw.Draw(mask).polygon(points, fill=255)
    return np.asarray(
        mask.resize((size, size), Image.BOX), dtype=np.float64
    ) / 255.0


def _ramp(stops, t):
    out = np.zeros(t.shape + (3,), dtype=np.float64)
    for (t0, c0), (t1, c1) in zip(stops, stops[1:]):
        band = (t >= t0) & (t <= t1)
        local = (t[band] - t0) / (t1 - t0)
        for channel in range(3):
            out[band, channel] = c0[channel] + local * (c1[channel] - c0[channel])
    out[t < stops[0][0]] = stops[0][1]
    out[t > stops[-1][0]] = stops[-1][1]
    return out


def _stroke_colour(size, scale=1.0):
    axis = (np.arange(size) + 0.5) * (CANVAS / size)
    xs, ys = np.meshgrid(axis, axis)
    centre = CANVAS / 2.0
    xs = centre + (xs - centre) / scale
    ys = centre + (ys - centre) / scale
    gx = STROKE_GRADIENT_END[0] - STROKE_GRADIENT_START[0]
    gy = STROKE_GRADIENT_END[1] - STROKE_GRADIENT_START[1]
    t = ((xs - STROKE_GRADIENT_START[0]) * gx +
         (ys - STROKE_GRADIENT_START[1]) * gy) / (gx * gx + gy * gy)
    return _ramp(STROKE_STOPS, np.clip(t, 0.0, 1.0))


def _rounded_rect_coverage(size):
    n = size * SUPERSAMPLE
    axis = (np.arange(n) + 0.5) * (CANVAS / n)
    xs, ys = np.meshgrid(axis, axis)
    half = CANVAS / 2.0
    inner = half - CORNER_RADIUS
    dx = np.abs(xs - half) - inner
    dy = np.abs(ys - half) - inner
    inside = (np.hypot(np.maximum(dx, 0.0), np.maximum(dy, 0.0))
              - CORNER_RADIUS) <= 0
    return inside.reshape(size, SUPERSAMPLE, size, SUPERSAMPLE).mean(axis=(1, 3))


def mark_alpha(size, scale=1.0):
    """Alpha of the interlaced mark.

    Each piece first clears a slightly-wider footprint out of everything
    drawn so far, then paints itself — leaving a clean gap where it crosses
    in front of an earlier piece.
    """
    # (segments, width profile, t range, punches a gap through what's below)
    # The V's rising half sets no gap: it only meets the falling half, at the
    # shared apex, and a gap there would bite a notch out of the point.
    pieces = [
        (STROKE_Z, WIDTH_Z, (0.0, 1.0), False),
        (STROKE_V_DOWN, WIDTH_V_DOWN, (0.0, 1.0), True),
        (STROKE_V_UP, WIDTH_V_UP, (0.0, 1.0), False),
        (STROKE_Z, WIDTH_Z, Z_OVER_RANGE, True),
    ]

    alpha = np.zeros((size, size), dtype=np.float64)
    for segments, profile, t_range, knocks_out in pieces:
        if knocks_out:
            knockout = _polygon_coverage(
                stroke_outline(
                    segments, profile, t_range=t_range, grow=WEAVE_GAP
                ),
                size, scale,
            )
            alpha *= 1.0 - knockout
        filled = _polygon_coverage(
            stroke_outline(segments, profile, t_range=t_range), size, scale
        )
        alpha = np.maximum(alpha, filled)
    return alpha


def render(size, *, backdrop, scale=1.0):
    alpha = mark_alpha(size, scale)
    rgb = _stroke_colour(size, scale)

    if backdrop:
        card = _rounded_rect_coverage(size)
        vertical = np.clip(
            np.tile(((np.arange(size) + 0.5) / size)[:, None], (1, size)),
            0.0, 1.0,
        )
        backdrop_rgb = _ramp(
            [(0.0, BACKDROP_TOP), (1.0, BACKDROP_BOTTOM)], vertical
        )
        # Mark over backdrop; the weave gaps fall through to the backdrop.
        rgb = backdrop_rgb * (1 - alpha[..., None]) + rgb * alpha[..., None]
        alpha = np.maximum(card, alpha * card)

    rgba = np.concatenate([rgb, alpha[..., None] * 255.0], axis=2)
    return Image.fromarray(np.round(rgba).astype(np.uint8), mode="RGBA")


# Android launcher densities, in px.
LEGACY_DENSITIES = {
    "mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192,
}
# Adaptive-icon layers are 108dp with only the inner 72dp (66%) guaranteed
# visible under every launcher mask.
ADAPTIVE_DENSITIES = {
    "mdpi": 108, "hdpi": 162, "xhdpi": 216, "xxhdpi": 324, "xxxhdpi": 432,
}
ADAPTIVE_MARK_SCALE = 0.86


def _svg_path(polygon):
    head = f"M {polygon[0][0]:.1f} {polygon[0][1]:.1f}"
    rest = " ".join(f"L {x:.1f} {y:.1f}" for x, y in polygon[1:])
    return f"{head} {rest} Z"


def build_svg(*, backdrop: bool) -> str:
    """The mark as SVG.

    The weave is built from masks rather than baked-in boolean geometry: the
    Z is masked by everything the V's falling stroke covers, the V is masked
    by the Z's bottom stroke, and the Z's bottom stroke is painted last on
    top — the same over/under alternation the rasterizer composites.
    """
    z_full = _svg_path(stroke_outline(STROKE_Z, WIDTH_Z))
    z_over = _svg_path(stroke_outline(STROKE_Z, WIDTH_Z, t_range=Z_OVER_RANGE))
    z_over_gap = _svg_path(
        stroke_outline(STROKE_Z, WIDTH_Z, t_range=Z_OVER_RANGE, grow=WEAVE_GAP)
    )
    v_down = _svg_path(stroke_outline(STROKE_V_DOWN, WIDTH_V_DOWN))
    v_down_gap = _svg_path(
        stroke_outline(STROKE_V_DOWN, WIDTH_V_DOWN, grow=WEAVE_GAP)
    )
    v_up = _svg_path(stroke_outline(STROKE_V_UP, WIDTH_V_UP))

    stops = "\n      ".join(
        f'<stop offset="{offset}" stop-color="#{r:02X}{g:02X}{b:02X}"/>'
        for offset, (r, g, b) in STROKE_STOPS
    )
    card = (
        f'  <rect x="0" y="0" width="512" height="512" rx="{CORNER_RADIUS:.0f}" '
        f'ry="{CORNER_RADIUS:.0f}" fill="url(#zivybbBackdrop)"/>\n'
        if backdrop else ""
    )
    backdrop_gradient = (
        '    <linearGradient id="zivybbBackdrop" x1="0" y1="0" x2="0" y2="512"\n'
        '        gradientUnits="userSpaceOnUse">\n'
        f'      <stop offset="0" stop-color="#{BACKDROP_TOP[0]:02X}'
        f'{BACKDROP_TOP[1]:02X}{BACKDROP_TOP[2]:02X}"/>\n'
        f'      <stop offset="1" stop-color="#{BACKDROP_BOTTOM[0]:02X}'
        f'{BACKDROP_BOTTOM[1]:02X}{BACKDROP_BOTTOM[2]:02X}"/>\n'
        '    </linearGradient>\n'
        if backdrop else ""
    )
    label = "Zivybb app icon" if backdrop else "Zivybb"

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" \
width="512" height="512" role="img" aria-label="{label}">
  <title>{label}</title>
  <!-- GENERATED by tools/zivybb_logo.py - do not edit by hand. Change the
       stroke geometry in that script and re-run it. -->
  <defs>
{backdrop_gradient}    <linearGradient id="zivybbStroke"
        x1="{STROKE_GRADIENT_START[0]:.0f}" y1="{STROKE_GRADIENT_START[1]:.0f}"
        x2="{STROKE_GRADIENT_END[0]:.0f}" y2="{STROKE_GRADIENT_END[1]:.0f}"
        gradientUnits="userSpaceOnUse">
      {stops}
    </linearGradient>
    <mask id="zivybbUnderV">
      <rect x="0" y="0" width="512" height="512" fill="#fff"/>
      <path d="{v_down_gap}" fill="#000"/>
    </mask>
    <mask id="zivybbUnderZ">
      <rect x="0" y="0" width="512" height="512" fill="#fff"/>
      <path d="{z_over_gap}" fill="#000"/>
    </mask>
  </defs>
{card}  <g fill="url(#zivybbStroke)">
    <path d="{z_full}" mask="url(#zivybbUnderV)"/>
    <path d="{v_down}" mask="url(#zivybbUnderZ)"/>
    <path d="{v_up}"/>
    <path d="{z_over}"/>
  </g>
</svg>
"""


def main() -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    images = os.path.join(root, "assets", "images")
    res = os.path.join(root, "android", "app", "src", "main", "res")
    os.makedirs(images, exist_ok=True)

    for name, backdrop in (("zivybb_logo", False), ("zivybb_icon", True)):
        with open(os.path.join(images, f"{name}.svg"), "w") as handle:
            handle.write(build_svg(backdrop=backdrop))
    print("wrote assets/images/zivybb_logo.svg, zivybb_icon.svg")

    render(512, backdrop=False).save(os.path.join(images, "zivybb_logo.png"))
    render(512, backdrop=True).save(os.path.join(images, "zivybb_icon.png"))
    print("wrote assets/images/zivybb_logo.png, zivybb_icon.png")

    for density, px in LEGACY_DENSITIES.items():
        folder = os.path.join(res, f"mipmap-{density}")
        os.makedirs(folder, exist_ok=True)
        render(px, backdrop=True).save(os.path.join(folder, "ic_launcher.png"))
    print("wrote mipmap-*/ic_launcher.png")

    for density, px in ADAPTIVE_DENSITIES.items():
        folder = os.path.join(res, f"mipmap-{density}")
        os.makedirs(folder, exist_ok=True)
        render(px, backdrop=False, scale=ADAPTIVE_MARK_SCALE).save(
            os.path.join(folder, "ic_launcher_foreground.png")
        )
    print("wrote mipmap-*/ic_launcher_foreground.png")


if __name__ == "__main__":
    main()
